<?php

namespace RioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AtlheteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtlheteRepository extends EntityRepository
{
}
